package utils

const (
	BadLatOrLonMsg              = "latitude and longitude must be numbers, optionally with a minus sign and decimal point"
	Error                       = "error"
	ErrorFetchGPD               = "failed to fetch grid point data: %v"
	ErrorInvalidCoord           = "invalid coordinates or location no supported by the NWS API"
	ErrorDecodeGridP            = "failed to decode gridpoint data: %v"
	ErrorURLNotFound            = "forecast URL not found in gridpoint data"
	ErrorFetchFD                = "failed to fetch forecast data: %v"
	ErrorFetchInvalidCoordOrLoc = "failed to fetch forecast data: invalid coordinates or location not supported"
	ErrorDecodeFD               = "failed to decode forecast data: %v"
	ErrorPropertiesNotFoundFD   = "properties not found in forecast data"
	ErrorNoPeriodsFound         = "no forecast periods found"
	ErrorFailedRedisConn        = "Failed to Connect to Redis:"
	ErrorFailMarshalWD          = "Failed to marshal weather data"
	ErrorFailUnMarshalCD        = "Failed to unmarshal cached data"
	ErrorFailCacheData          = "Failed to Cache Weather Data: "
	ErrorFailRetrCacheData      = "Failed to Retrieve Cached Data: "
	ErrorRedisSetErr            = "Redis Set error:"
	ErrorRedisGetErr            = "Redis Get error:"
	ErrorFailTokenGen           = "Failed to generate token"
	Expiry                      = "exp"
	LatQueryParam               = "lat"
	LonQueryParam               = "lon"
	Properties                  = "properties"
	SuccessRedisConn            = "Connected to Redis Succesfully!"
	Token                       = "token"
	Usr                         = "username"
	Weather                     = "weather"

	ContentType          = "X-Content-Type-Options"
	ContentTypeVal       = "nosniff"
	FrameOptions         = "X-Frame-Options"
	FrameOptionsVal      = "DENY"
	SecurityPolicy       = "Content-Security-Policy"
	SecurityPolicyVal    = "default-src 'self'"
	XSSProtection        = "X-XSS-Protection"
	XSSProtectioVal      = "1; mode=block"
	ReferrerPolicy       = "Referrer-Policy"
	ReferrerPolicyVal    = "strict-origin-when-cross-origin"
	PermissionsPolicy    = "Permissions-Policy"
	PermissionsPolicyVal = "geolocation=(self)"
)
